// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type User struct {
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
